//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DScaler.rc
//
#define IDB_CZECH_VTCHARS               100
#define IDB_FMINUS                      101
#define IDB_FPLUS                       102
#define IDB_FRENCH_VTCHARS              103
#define IDB_GERMAN_VTCHARS              104
#define IDB_GREEK_VTCHARS               105
#define IDB_RUSSIAN_VTCHARS             106
#define IDB_STARTUP                     107
#define IDB_VTCHARS                     108
#define IDI_DSCALER                     109
#define IDB_HEBREW_VTCHARS              111
#define IDB_HUNGARIAN_VTCHARS           112
#define IDB_BITMAP1                     112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         0
#define _APS_NEXT_CONTROL_VALUE         0
#define _APS_NEXT_SYMED_VALUE           210
#endif
#endif
